nelmio_cors:
    defaults:
        allow_credentials: false
        allow_origin: ['*']
        allow_headers: ['*']
        allow_methods: ['GET','POST','OPTIONS','DELETE','PUT']
        max_age: 0
    paths:
        '^/api/':
            max_age: 3600